export const images = {
  logo: require("../assets/logo.jpg"),
  //   menu: require("../assets/menu.jpg"),
  //   basket: require("../assets/basket.jpg"),
  //   cart: require("../assets/cart.jpg"),
  //   order: require("../assets/order.jpg"),
  //   user: require("../assets/user.jpg"),
  restaurant: require("../assets/restaurant.jpg"),
  //   table: require("../assets/table.jpg"),
  //   payment: require("../assets/payment.jpg"),
  //   checkout: require("../assets/checkout.jpg"),
  reservation: require("../assets/reservation.jpg"),
  dinein: require("../assets/dinein.jpg"),
  //   admin: require("../assets/admin.jpg"),
  //   manage: require("../assets/manage.jpg"),
  //   users: require("../assets/users.jpg"),
  //   orders: require("../assets/orders.jpg"),
  delivery: require("../assets/delivery.jpg"),
  fufu: require("../assets/Fufu.jpg"),
  ndole: require("../assets/ndole.jpg"),
  rice: require("../assets/rice.jpg"),
  //   tablereservation: require("../assets/tablereservation.jpg"),
  bg: require("../assets/image.png"),
};
