export const menuItems = [
  {
    id: "1",
    name: "Grilled Chicken",
    description: "Juicy grilled chicken with spices",
    price: "1500FCFA",
    image: require("../assets/chicken.jpg"),
    category: "Dinner",
  },
  {
    id: "2",
    name: "Spaghetti Carbonara",
    description: "Creamy spaghetti with bacon",
    price: "500FCFA",
    image: require("../assets/spaghetti.jpg"),
    category: "Dinner",
  },
  {
    id: "3",
    name: "Cheese Pizza",
    description: "Delicious cheesy pizza with toppings",
    price: "1000FCFA",
    image: require("../assets/pizza.jpg"),
    category: "Dessert",
  },
  {
    id: "4",
    name: "Fried Rice",
    description: "Special fried rice with veggies",
    price: "1000FCFA",
    image: require("../assets/rice.jpg"),
    category: "Dinner",
  },
  {
    id: "5",
    name: "Cakes",
    description: "Sweet and tasty cakes",
    price: "500FCFA",
    image: require("../assets/cake.jpg"),
    category: "Dessert",
  },
  {
    id: "6",
    name: "Pancakes",
    description: "Soft pancakes with syrup",
    price: "200FCFA",
    image: require("../assets/pancakes.jpg"),
    category: "Breakfast",
  },
  {
    id: "7",
    name: "Coffee",
    description: "Hot coffee",
    price: "300FCFA",
    image: require("../assets/pure.jpg"),
    category: "Breakfast",
  },
  {
    id: "8",
    name: "Achu",
    description: "Traditional Cameroonian dish",
    price: "1000FCFA",
    image: require("../assets/IMG_3.jpg"),
    category: "Lunch",
  },
  {
    id: "9",
    name: "Ndole",
    description: "Cameroonian dish with spinach and peanuts",
    price: "700FCFA",
    image: require("../assets/ndole.jpg"),
    category: "Lunch",
  },
  {
    id: "10",
    name: "Fish Roll",
    description: "Crispy fried fish rolls",
    price: "100FCFA",
    image: require("../assets/fries.jpg"),
    category: "Snacks",
  },
  {
    id: "11",
    name: "Plantains",
    description: "Fried or boiled plantains",
    price: "500FCFA",
    image: require("../assets/IMG_9.jpg"),
    category: "lunch",
  },
  {
    id: "12",
    name: "Fries",
    description: "Crispy fried fries",
    price: "300FCFA",
    image: require("../assets/Frenchfries.jpg"),
    category: "Snacks",
  },
  {
    id: "13",
    name: "Hotdog",
    description: "Hotties",
    price: "200FCFA",
    image: require("../assets/Hotdog.jpg"),
    category: "Snacks",
  },
  {
    id: "14",
    name: "Fufu",
    description: "Smooth",
    price: "500FCFA",
    image: require("../assets/Fufu.jpg"),
    category: "Lunch",
  },
  {
    id: "15",
    name: "Hotdog",
    description: "Hotties",
    price: "200FCFA",
    image: require("../assets/Hotdog.jpg"),
    category: "Breakfast",
  },
  {
    id: "7",
    name: "Coffee",
    description: "Hot coffee",
    price: "300FCFA",
    image: require("../assets/pure.jpg"),
    category: "Dessert",
  },
];
